version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - LOG_LEVEL=INFO
      - WEATHER_API_KEY=demo-key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Para desarrollo con hot reload
  flask-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - /app/venv
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    profiles:
      - dev